### ISSUE TITLE
Use a crate to conform to correct config location 

### ISSUE THREAD

**Issue by barskern** [arzg/vim-strand#1]
Instead of manually trying to locate the correct directory for configs, you could use [directories](https://crates.io/crates/directories) (which is even cross platform).

**Comment by lunacookies** [comment]
In fact, I am using a crate to locate the correct config location – `dirs`. However, this uses a location in `~/Library/Preferences` on macOS. This is the canonical location for GUI apps, but not for CLIs, so I opted to manually override `dirs`’s solution for macOS builds. I copied most of that code from bat, which [had an interesting discussion on this very topic](https://github.com/sharkdp/bat/issues/151) (you can find the actual PR [here](https://github.com/sharkdp/bat/pull/491)). You do have a point, however, that `directories` might be more appropriate than `dirs` in this case.

**Comment by barskern** [comment]
Ah I was a bit too quick on the suggestive trigger as I did not notice `dirs`.

The discussion is rather interesting. Personally I use Linux and use `~/.config/` for all my configuration, so the issue doesn't directly concern me, however I do think a `directories` is a nice abstraction. Good luck with the choice :smile:

**Comment by lunacookies** [comment]
Thanks. I’m still not happy with the current solution, so if anyone knows of a better way, I’m all ears!
