### ISSUE TITLE
permission denied

### ISSUE THREAD

**Issue by adeyahya** [arzg/vim-strand#11]
after installing strand using `linuxbrew`, got permission error when executing `strand`

```bash
-bash: /home/linuxbrew/.linuxbrew/bin/strand: Permission denied
```

**Comment by lunacookies** [comment]
I think you need to `chmod +x` it.

**Comment by adeyahya** [comment]
I need to replicate it again to make sure, I already install it using different approach. since then, ill close the issue, thanks.
